import { escXml } from '../maml.js';

export default {
  id: 'action_buttons', icon: '⚡', name: '快捷按钮', desc: 'Button 交互面板，可触发命令',
  updater: 'DateTime.Minute',
  config: [
    { group: '基本', fields: [
      { key: 'cardName', label: '卡片名称', type: 'text', default: '快捷按钮' },
      { key: 'bgColor', label: '背景颜色', type: 'color', default: '#0d1117' },
    ]},
    { group: '样式', fields: [
      { key: 'btnColor', label: '按钮颜色', type: 'color', default: '#1a1a2e' },
      { key: 'accentColor', label: '强调色', type: 'color', default: '#6c5ce7' },
      { key: 'textColor', label: '文字颜色', type: 'color', default: '#ffffff' },
    ]},
  ],
  elements(c) {
    return [
      { type: 'rectangle', x: 0, y: 0, w: 976, h: 596, color: c.bgColor, locked: true },
      { type: 'text', text: '快捷操作', x: 30, y: 30, size: 18, color: c.textColor, bold: true, locked: true },
      { type: 'rectangle', x: 30, y: 70, w: 100, h: 44, color: c.btnColor, radius: 10, locked: false },
      { type: 'text', text: '🔊 音量', x: 46, y: 82, size: 13, color: c.textColor, locked: false },
      { type: 'rectangle', x: 140, y: 70, w: 100, h: 44, color: c.btnColor, radius: 10, locked: false },
      { type: 'text', text: '📶 WiFi', x: 158, y: 82, size: 13, color: c.textColor, locked: false },
      { type: 'rectangle', x: 30, y: 124, w: 100, h: 44, color: c.btnColor, radius: 10, locked: false },
      { type: 'text', text: '🔵 蓝牙', x: 46, y: 136, size: 13, color: c.textColor, locked: false },
      { type: 'rectangle', x: 140, y: 124, w: 100, h: 44, color: c.btnColor, radius: 10, locked: false },
      { type: 'text', text: '🔆 亮度', x: 158, y: 136, size: 13, color: c.textColor, locked: false },
    ];
  },
  rawXml(c) {
    return [
      '<Widget screenWidth="976" frameRate="0" scaleByDensity="false" useVariableUpdater="DateTime.Minute" name="' + escXml(c.cardName || '快捷按钮') + '">',
      '  <Var name="marginL" type="number" expression="(#view_width * 0.30)" />',
      '',
      '  <!-- 背景 -->',
      '  <Rectangle w="#view_width" h="#view_height" fillColor="' + c.bgColor + '" />',
      '',
      '  <Group x="#marginL" y="0">',
      '    <Text x="0" y="30" size="18" color="' + c.textColor + '" text="快捷操作" bold="true" />',
      '',
      '    <!-- 按钮 1: 音量 -->',
      '    <Button name="btn_volume" x="0" y="70" w="100" h="44">',
      '      <Rectangle x="0" y="0" w="100" h="44" fillColor="' + c.btnColor + '" cornerRadius="10" />',
      '      <Text x="16" y="12" size="13" color="' + c.textColor + '" text="🔊 音量" />',
      '      <Trigger action="click">',
      '        <BinderCommand target="volume_up" value="1" />',
      '      </Trigger>',
      '    </Button>',
      '',
      '    <!-- 按钮 2: WiFi -->',
      '    <Button name="btn_wifi" x="110" y="70" w="100" h="44">',
      '      <Rectangle x="0" y="0" w="100" h="44" fillColor="' + c.btnColor + '" cornerRadius="10" />',
      '      <Text x="16" y="12" size="13" color="' + c.textColor + '" text="📶 WiFi" />',
      '      <Trigger action="click">',
      '        <BinderCommand target="wifi_toggle" value="1" />',
      '      </Trigger>',
      '    </Button>',
      '',
      '    <!-- 按钮 3: 蓝牙 -->',
      '    <Button name="btn_bt" x="0" y="124" w="100" h="44">',
      '      <Rectangle x="0" y="0" w="100" h="44" fillColor="' + c.btnColor + '" cornerRadius="10" />',
      '      <Text x="16" y="12" size="13" color="' + c.textColor + '" text="🔵 蓝牙" />',
      '      <Trigger action="click">',
      '        <BinderCommand target="bt_toggle" value="1" />',
      '      </Trigger>',
      '    </Button>',
      '',
      '    <!-- 按钮 4: 亮度 -->',
      '    <Button name="btn_brightness" x="110" y="124" w="100" h="44">',
      '      <Rectangle x="0" y="0" w="100" h="44" fillColor="' + c.btnColor + '" cornerRadius="10" />',
      '      <Text x="16" y="12" size="13" color="' + c.textColor + '" text="🔆 亮度" />',
      '      <Trigger action="click">',
      '        <BinderCommand target="brightness_auto" value="1" />',
      '      </Trigger>',
      '    </Button>',
      '',
      '    <!-- 底部提示 -->',
      '    <Text x="0" y="190" size="10" color="#444444" text="点击按钮触发快捷操作" />',
      '  </Group>',
      '</Widget>',
    ].join('\n');
  },
};
