import { escXml } from '../maml.js';

export default {
  id: 'streak_tracker', icon: '🔥', name: '打卡追踪', desc: '连续打卡天数 + 本周记录',
  updater: 'DateTime.Day',
  config: [
    { group: '基本', fields: [
      { key: 'cardName', label: '卡片名称', type: 'text', default: '打卡追踪' },
      { key: 'bgColor', label: '背景颜色', type: 'color', default: '#1a0a0a' },
      { key: 'habitName', label: '习惯名称', type: 'text', default: '早起' },
      { key: 'streakDays', label: '当前连续天数', type: 'range', min: 0, max: 365, default: 12 },
    ]},
    { group: '样式', fields: [
      { key: 'fireColor', label: '火焰颜色', type: 'color', default: '#ff6b35' },
      { key: 'numColor', label: '数字颜色', type: 'color', default: '#ffffff' },
      { key: 'labelColor', label: '标签颜色', type: 'color', default: '#888888' },
      { key: 'doneColor', label: '完成标记颜色', type: 'color', default: '#00e676' },
      { key: 'missColor', label: '未完成颜色', type: 'color', default: '#333333' },
    ]},
  ],
  elements(c) {
    var streak = Number(c.streakDays) || 12;
    return [
      { type: 'rectangle', x: 0, y: 0, w: 976, h: 596, color: c.bgColor, locked: true },
      { type: 'text', text: '🔥', x: 30, y: 30, size: 36, color: c.fireColor },
      { type: 'text', text: c.habitName || '早起', x: 80, y: 50, size: 16, color: c.labelColor },
      { type: 'text', text: String(streak), x: 30, y: 90, size: 72, color: c.fireColor, bold: true, fontFamily: 'mipro-demibold' },
      { type: 'text', text: '天连续', x: 30, y: 170, size: 18, color: c.numColor },
      { type: 'rectangle', x: 30, y: 200, w: 250, h: 1, color: '#333333' },
      { type: 'text', text: '本周', x: 30, y: 220, size: 13, color: c.labelColor },
      { type: 'circle', x: 50, y: 255, r: 12, color: c.doneColor },
      { type: 'circle', x: 90, y: 255, r: 12, color: c.doneColor },
      { type: 'circle', x: 130, y: 255, r: 12, color: c.doneColor },
      { type: 'circle', x: 170, y: 255, r: 12, color: c.doneColor },
      { type: 'circle', x: 210, y: 255, r: 12, color: c.missColor },
      { type: 'text', text: '日 一 二 三 四 五 六', x: 26, y: 280, size: 10, color: c.labelColor },
    ];
  },
  rawXml(c) {
    var habit = escXml(c.habitName || '早起');
    var streak = Number(c.streakDays) || 12;
    return [
      '<Widget screenWidth="976" frameRate="0" scaleByDensity="false" useVariableUpdater="DateTime.Day" name="' + escXml(c.cardName || '打卡追踪') + '">',
      '  <Var name="marginL" type="number" expression="(#view_width * 0.25)" />',
      '  <Var name="dow" type="number" expression="dayOfWeek(#time_sys)" />',
      '',
      '  <!-- 持久化连续天数 -->',
      '  <Permanence name="streak_count" expression="' + streak + '" />',
      '  <Permanence name="streak_today_done" expression="0" />',
      '',
      '  <!-- 背景 -->',
      '  <Rectangle w="#view_width" h="#view_height" fillColor="' + c.bgColor + '" />',
      '',
      '  <Group x="#marginL" y="0">',
      '    <!-- 火焰图标 -->',
      '    <Text x="0" y="20" size="36" color="' + c.fireColor + '" text="🔥" />',
      '',
      '    <!-- 习惯名称 -->',
      '    <Text x="50" y="40" size="16" color="' + c.labelColor + '" text="' + habit + '" />',
      '',
      '    <!-- 连续天数 -->',
      '    <Text x="0" y="80" size="72" color="' + c.fireColor + '" textExp="#streak_count" bold="true" fontFamily="mipro-demibold" />',
      '',
      '    <!-- "天连续" -->',
      '    <Text x="0" y="160" size="18" color="' + c.numColor + '" text="天连续" />',
      '',
      '    <!-- 分隔线 -->',
      '    <Rectangle x="0" y="190" w="250" h="1" fillColor="#333333" />',
      '',
      '    <!-- 本周标题 -->',
      '    <Text x="0" y="210" size="13" color="' + c.labelColor + '" text="本周" />',
      '',
      '    <!-- 本周圆点 (日-六) -->',
      '    <Circle x="20" y="245" r="12" fillColor="' + c.doneColor + '" />',
      '    <Circle x="60" y="245" r="12" fillColor="' + c.doneColor + '" />',
      '    <Circle x="100" y="245" r="12" fillColor="' + c.doneColor + '" />',
      '    <Circle x="140" y="245" r="12" fillColor="' + c.doneColor + '" />',
      '    <Circle x="180" y="245" r="12" fillColor="' + c.missColor + '" />',
      '    <Circle x="220" y="245" r="12" fillColor="' + c.missColor + '" />',
      '    <Circle x="260" y="245" r="12" fillColor="' + c.missColor + '" />',
      '',
      '    <!-- 星期标签 -->',
      '    <Text x="6" y="270" size="10" color="' + c.labelColor + '" text="日 一 二 三 四 五 六" />',
      '',
      '    <!-- 打卡按钮 -->',
      '    <Button name="btn_checkin" x="0" y="290" w="100" h="32">',
      '      <Rectangle x="0" y="0" w="100" h="32" fillColor="' + c.fireColor + '" cornerRadius="6" />',
      '      <Text x="20" y="8" size="13" color="#ffffff" text="✅ 打卡" bold="true" />',
      '      <Trigger action="click">',
      '        <VariableCommand target="streak_today_done" value="1" />',
      '      </Trigger>',
      '    </Button>',
      '  </Group>',
      '</Widget>',
    ].join('\n');
  },
};
